from __future__ import annotations

# ruff: noqa: E501,RUF001
import json
from html import escape
from typing import Any


def render_review_html(payload: dict[str, Any]) -> str:
    safe_json = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    title = escape(str(payload.get("title", "Binance 价格行为复盘")))
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
:root{{--canvas:#070a0e;--surface:#0d1218;--surface-2:#121922;--surface-3:#18212c;--border:#253140;--border-strong:#344457;--text:#e7edf5;--muted:#8896a8;--faint:#596779;--buy:#2d9cff;--buy-soft:#153a5c;--sell:#ffb020;--sell-soft:#49351c;--up:#23c98b;--down:#f05f70;--good:#4dd69d;--bad:#ff7180;--warn:#f3bd62;--review:#d7a84d;--mono:"IBM Plex Mono","SFMono-Regular",Consolas,monospace;--sans:"IBM Plex Sans","Noto Sans SC","PingFang SC",sans-serif;color-scheme:dark;font-family:var(--sans)}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--canvas);color:var(--text);font-size:13px}}button,input{{font:inherit}}button{{color:inherit}}main{{max-width:1880px;margin:auto;padding:14px 16px 28px}}
.topbar{{display:grid;grid-template-columns:minmax(310px,1fr) auto;align-items:end;gap:18px;padding:10px 2px 14px;border-bottom:1px solid var(--border)}}.kicker{{font:700 10px/1 var(--mono);letter-spacing:.2em;color:var(--review)}}h1{{font-size:22px;line-height:1.2;margin:7px 0 4px;letter-spacing:-.02em}}.subtitle{{margin:0;color:var(--muted);font-size:12px}}.stats{{display:flex;gap:1px;border:1px solid var(--border);background:var(--border);border-radius:6px;overflow:hidden}}.stat{{min-width:112px;padding:9px 11px;background:var(--surface)}}.stat small{{display:block;color:var(--muted);font-size:10px;margin-bottom:4px}}.stat strong{{font:650 14px/1 var(--mono)}}.stat.pnl.positive strong{{color:var(--up)}}.stat.pnl.negative strong{{color:var(--down)}}
.controlbar{{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:12px;min-height:42px;margin:10px 0;background:rgba(13,18,24,.97);border:1px solid var(--border);border-radius:6px;padding:6px 9px;box-shadow:0 10px 30px rgba(0,0,0,.24);backdrop-filter:blur(12px)}}.control-label{{color:var(--faint);font:700 10px var(--mono);letter-spacing:.12em}}.layer-toggles{{display:flex;align-items:center;gap:3px;flex-wrap:wrap}}.layer-toggle{{display:inline-flex;align-items:center;gap:6px;height:28px;padding:0 9px;border:1px solid transparent;border-radius:4px;color:var(--muted);cursor:pointer;user-select:none}}.layer-toggle:hover{{background:var(--surface-3);color:var(--text)}}.layer-toggle:has(input:checked){{background:#172333;border-color:#2e435a;color:#dbeaff}}.layer-toggle input{{position:absolute;opacity:0;pointer-events:none}}.trade-key{{margin-left:auto;display:flex;gap:10px;color:var(--muted);font-size:11px;white-space:nowrap}}.trade-key span{{display:flex;align-items:center;gap:5px}}.trade-key i{{width:9px;height:9px;border-radius:2px;background:var(--buy)}}.trade-key .exit i{{background:var(--sell)}}
.episode-nav{{display:flex;gap:5px;overflow:auto;padding:0 0 10px;scrollbar-width:thin}}.episode-nav button{{flex:0 0 auto;border:1px solid var(--border);background:var(--surface);border-radius:4px;padding:7px 10px;cursor:pointer;text-align:left}}.episode-nav button:hover{{border-color:var(--border-strong);background:var(--surface-2)}}.episode-nav b{{display:block;font:700 11px var(--mono)}}.episode-nav small{{display:inline-block;color:#fff;font:750 10px var(--mono);margin-top:5px;padding:3px 6px;border-radius:3px}}.episode-nav small.positive{{background:#176a4c}}.episode-nav small.negative{{background:#8a3040}}.episode-nav small.open{{background:#445165;color:#d6deea}}
.trade-ledger{{border:1px solid var(--border);border-radius:6px;background:var(--surface);margin-bottom:10px;overflow:hidden}}.ledger-head{{display:flex;align-items:baseline;justify-content:space-between;padding:10px 12px;border-bottom:1px solid var(--border)}}.ledger-head h2{{font-size:12px;letter-spacing:.08em;margin:0}}.ledger-head p{{font-size:10px;color:var(--muted);margin:0}}.trade-table-wrap{{overflow:auto}}.trade-table{{width:100%;border-collapse:collapse;min-width:1060px}}.trade-table th{{position:sticky;top:0;background:#111820;color:var(--muted);font-size:9px;letter-spacing:.08em;text-align:left;padding:7px 9px;border-bottom:1px solid var(--border)}}.trade-table td{{padding:8px 9px;border-bottom:1px solid #1a2430;font-size:10px;vertical-align:middle}}.trade-table tr:last-child td{{border-bottom:0}}.trade-table tbody tr{{cursor:pointer}}.trade-table tbody tr:hover{{background:#121b25}}.trade-table .instrument{{font:700 11px var(--mono)}}.trade-table .route{{font:10px var(--mono);color:#c5cfda}}.trade-table .number{{font:700 10px var(--mono);text-align:right}}.trade-table .number.positive{{color:var(--up)}}.trade-table .number.negative{{color:var(--down)}}.result-badge{{display:inline-flex;align-items:center;justify-content:center;min-width:58px;padding:4px 7px;border-radius:3px;font-weight:800}}.result-badge.profit{{background:#153f33;color:#64dfac}}.result-badge.loss{{background:#4c242c;color:#ff8b97}}.result-badge.open{{background:#283443;color:#c5d0dd}}.process-badge{{display:inline-block;padding:3px 6px;border:1px solid var(--border);border-radius:3px;color:#c5d0dc}}.key-issue{{max-width:310px;color:#aeb9c6;line-height:1.35}}
.summary-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}}.summary{{border:1px solid var(--border);background:var(--surface);border-radius:6px;padding:10px 12px}}.summary h2{{font-size:11px;letter-spacing:.08em;margin:0 0 6px;color:var(--muted)}}.summary ul{{margin:0;padding-left:17px;color:#b6c1ce;font-size:11px;line-height:1.65}}
.episode{{scroll-margin-top:58px;border:1px solid var(--border);background:var(--surface);border-radius:7px;margin:12px 0 20px;overflow:hidden;box-shadow:0 14px 38px rgba(0,0,0,.18)}}.episode-head{{display:flex;align-items:center;gap:12px;min-height:54px;padding:9px 12px;border-bottom:1px solid var(--border);background:linear-gradient(90deg,#111820,#0d1218)}}.symbol-block h2{{font:750 17px/1 var(--mono);margin:0}}.symbol-block p{{margin:4px 0 0;color:var(--muted);font:10px var(--mono)}}.direction{{padding:4px 7px;border-radius:3px;font-size:10px;font-weight:800}}.direction.long{{color:#8cc8ff;background:var(--buy-soft)}}.direction.short{{color:#ffc86d;background:var(--sell-soft)}}.price-route{{display:flex;align-items:center;gap:8px;margin-left:8px;font:12px var(--mono);color:#c8d2de}}.price-route .arrow{{color:var(--faint)}}.episode-metrics{{margin-left:auto;display:flex;align-items:center;gap:14px}}.metric{{text-align:right}}.metric small{{display:block;color:var(--muted);font-size:9px;margin-bottom:2px}}.metric strong{{font:700 12px var(--mono)}}.metric strong.positive{{color:var(--up)}}.metric strong.negative{{color:var(--down)}}.outcome{{padding:5px 8px;border-radius:3px;font-size:10px;font-weight:700;border:1px solid var(--border)}}.outcome.good{{color:var(--good);border-color:#276a51}}.outcome.bad{{color:var(--bad);border-color:#75323a}}.outcome.unknown{{color:var(--warn);border-color:#6e5830}}
.verdict-band{{display:grid;grid-template-columns:minmax(240px,.7fr) minmax(260px,1fr);border-bottom:1px solid var(--border);background:#0a1016}}.financial-result,.process-result{{display:flex;align-items:center;gap:10px;padding:10px 12px}}.financial-result{{border-right:1px solid var(--border)}}.financial-result strong{{font:800 19px var(--mono)}}.financial-result.profit strong{{color:var(--up)}}.financial-result.loss strong{{color:var(--down)}}.financial-result.open strong{{color:#c7d1dc}}.verdict-band small{{display:block;color:var(--muted);font-size:9px;letter-spacing:.08em;margin-bottom:2px}}.process-result b{{font-size:12px}}.process-result span{{color:var(--muted);font-size:10px}}.decision-brief{{display:grid;grid-template-columns:1.1fr 1.1fr 1.3fr;gap:7px;margin-bottom:9px}}.brief-card{{position:relative;min-height:92px;border:1px solid var(--border);border-top:2px solid #53677d;border-radius:4px;background:#101720;padding:9px 10px 9px 40px}}.brief-card.problem{{border-top-color:var(--bad)}}.brief-card.action{{border-top-color:var(--review);background:#15160f}}.brief-index{{position:absolute;left:10px;top:10px;color:#526173;font:800 13px var(--mono)}}.brief-card h3{{font-size:10px;letter-spacing:.08em;margin:0 0 6px;color:#aab6c4}}.brief-card p{{margin:0;color:#d5dde6;font-size:10px;line-height:1.55}}.brief-card.action p{{color:#f0dfb4}}
.episode-body{{display:grid;grid-template-columns:minmax(0,1fr) 354px;min-height:640px}}.workspace{{min-width:0;padding:10px 12px 12px}}.trade-strip{{display:flex;align-items:stretch;gap:5px;overflow:auto;margin-bottom:9px;padding-bottom:2px;scrollbar-width:thin}}.trade-chip{{position:relative;flex:0 0 auto;display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center;min-width:152px;padding:7px 9px;border:1px solid var(--border);border-radius:4px;background:var(--surface-2);cursor:pointer}}.trade-chip:hover{{border-color:var(--border-strong);transform:translateY(-1px)}}.trade-chip.open{{box-shadow:inset 3px 0 var(--buy)}}.trade-chip.close{{box-shadow:inset 3px 0 var(--sell)}}.trade-chip .trade-icon{{display:grid;place-items:center;width:26px;height:26px;border-radius:3px;font:800 10px var(--mono)}}.trade-chip.open .trade-icon{{background:var(--buy-soft);color:#92cbff}}.trade-chip.close .trade-icon{{background:var(--sell-soft);color:#ffd184}}.trade-chip b{{display:block;font-size:10px}}.trade-chip small{{display:block;color:var(--muted);font:10px var(--mono);margin-top:2px}}.trade-chip.active{{border-color:#d8e4f1;box-shadow:inset 3px 0 currentColor,0 0 0 1px rgba(255,255,255,.12)}}
.chart-toolbar{{display:flex;align-items:center;min-height:36px;border:1px solid var(--border);border-bottom:0;border-radius:5px 5px 0 0;background:var(--surface-2);padding:4px 7px}}.timeframes{{display:flex;gap:2px}}.tf-button{{min-width:44px;height:27px;border:0;background:transparent;border-radius:3px;color:var(--muted);font:700 11px var(--mono);cursor:pointer}}.tf-button:hover{{color:var(--text);background:var(--surface-3)}}.tf-button.active{{background:#284868;color:#fff}}.chart-context{{margin-left:10px;color:var(--muted);font-size:10px}}.chart-context b{{color:#cbd5e1;font-weight:600}}.chart-hint{{margin-left:auto;color:var(--faint);font-size:10px}}.chart-tools{{display:flex;align-items:center;gap:3px;margin-left:9px}}.chart-tool{{height:27px;min-width:29px;padding:0 8px;border:1px solid var(--border);border-radius:3px;background:#101720;color:#b8c4d1;font:700 11px var(--mono);cursor:pointer}}.chart-tool:hover{{border-color:var(--border-strong);background:var(--surface-3);color:#fff}}.chart-tool.reset{{min-width:42px;font-size:10px}}
.chart-stage{{position:relative;border:1px solid var(--border);border-radius:0 0 5px 5px;background:#080d13;overflow:hidden}}.chart-panel{{display:none}}.chart-panel.active{{display:block}}canvas{{display:block;width:100%;height:520px;cursor:grab;touch-action:none}}canvas.dragging{{cursor:grabbing}}.chart-tooltip{{position:absolute;display:none;z-index:5;pointer-events:none;min-width:170px;padding:7px 9px;border:1px solid var(--border-strong);border-radius:4px;background:rgba(10,15,21,.96);box-shadow:0 8px 22px rgba(0,0,0,.36);font:10px/1.55 var(--mono);color:#dbe4ee}}.chart-tooltip b{{color:#fff}}.chart-legend{{display:flex;gap:14px;align-items:center;padding:7px 2px 0;color:var(--muted);font-size:10px}}.chart-legend span{{display:flex;align-items:center;gap:5px}}.chart-legend i{{display:inline-block;width:14px;height:2px;background:var(--warn)}}.chart-legend .decision i{{border-top:1px dashed #8fa0b4;background:none}}.chart-legend .entry i{{height:8px;width:8px;border-radius:1px;background:var(--buy)}}.chart-legend .exit i{{height:8px;width:8px;border-radius:1px;background:var(--sell)}}
.review-side{{border-left:1px solid var(--border);background:var(--surface-2);display:flex;flex-direction:column;min-width:0}}.side-tabs{{display:flex;border-bottom:1px solid var(--border);padding:5px 6px 0}}.side-tab{{height:31px;padding:0 11px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);font-size:11px;cursor:pointer}}.side-tab.active{{color:var(--text);border-color:var(--review)}}.side-pane{{display:none;padding:10px;overflow:auto;max-height:684px}}.side-pane.active{{display:block}}.dimension{{padding:8px 9px;border:1px solid var(--border);border-radius:4px;margin:0 0 6px;background:#101720}}.dimension header{{display:flex;justify-content:space-between;gap:8px}}.dimension b{{font-size:11px}}.dimension em{{font-style:normal;font-size:9px}}.dimension.correct em{{color:var(--good)}}.dimension.improve em{{color:var(--bad)}}.dimension.unknown em{{color:var(--warn)}}.dimension p{{font-size:10px;color:var(--muted);line-height:1.5;margin:5px 0 0}}.ann{{font-size:10px;line-height:1.5;border-left:2px solid var(--border-strong);padding:6px 8px;margin:0 0 6px;background:#101720;color:var(--muted);cursor:pointer}}.ann:hover{{background:#151e29}}.ann.correct{{border-color:var(--good)}}.ann.improve{{border-color:var(--bad)}}.ann strong{{color:var(--text)}}.ann-meta{{display:flex;justify-content:space-between;margin-bottom:3px;color:var(--faint);font:9px var(--mono)}}
footer{{color:var(--muted);font-size:10px;line-height:1.6;padding:8px 2px 20px}}
@media(max-width:1180px){{.episode-body{{grid-template-columns:minmax(0,1fr) 310px}}.episode-metrics .metric:nth-child(2){{display:none}}}}
@media(max-width:900px){{main{{padding:10px}}.topbar{{display:block}}.stats{{margin-top:12px;overflow:auto}}.summary-grid{{grid-template-columns:1fr}}.episode-body{{display:block}}.review-side{{border-left:0;border-top:1px solid var(--border)}}.side-pane{{max-height:none}}canvas{{height:430px}}.episode-head{{flex-wrap:wrap}}.episode-metrics{{width:100%;margin-left:0;justify-content:flex-end}}.trade-key{{display:none}}.decision-brief{{grid-template-columns:1fr}}.chart-hint{{display:none}}}}
@media(max-width:560px){{.stat{{min-width:100px}}.price-route{{order:5;width:100%;margin-left:0}}canvas{{height:360px}}.chart-context{{display:none}}.verdict-band{{grid-template-columns:1fr}}.financial-result{{border-right:0;border-bottom:1px solid var(--border)}}.chart-tool{{padding:0 6px;min-width:27px}}}}
</style>
</head>
<body><main>
<header class="topbar"><div><div class="kicker">REPLAYTUTOR · REVIEW MODE</div><h1>{title}</h1><p class="subtitle" id="subtitle"></p></div><div class="stats" id="stats"></div></header>
<div class="controlbar"><span class="control-label">图层</span><div class="layer-toggles" id="toolbar"></div><div class="trade-key"><span><i></i>开仓 / 加仓</span><span class="exit"><i></i>减仓 / 平仓</span></div></div>
<nav class="episode-nav" id="episode-nav" aria-label="交易列表"></nav>
<section class="trade-ledger" id="ledger"></section>
<section class="summary-grid" id="summary"></section>
<section id="episodes"></section>
<footer>成交与行情来自 Binance；所有 decision_time 标注仅使用入场前已收盘 K 线。价格行为规则来自本地 price-action-coach、price-action-thinking、price-action-trading-ranges 与 check-trade-edge。自动复盘用于训练，不构成收益承诺或自动交易指令。</footer>
</main>
<script id="payload" type="application/json">{safe_json}</script>
<script>
const data=JSON.parse(document.getElementById("payload").textContent);
const layers=["background","location","setup","trigger","execution","management"];
const layerNames={{background:"背景",location:"位置",setup:"Setup",trigger:"触发",execution:"执行",management:"管理"}};
const active=new Set(layers);
const chartState=new Map();
const chartViewport=new Map();
const money=v=>Number(v||0).toLocaleString("zh-CN",{{maximumFractionDigits:4}});
const roleNames={{open:"开仓",add:"加仓",reduce:"减仓",close:"平仓"}};
const roleCodes={{open:"IN",add:"ADD",reduce:"CUT",close:"OUT"}};
const verdictNames={{correct:"做得对",improve:"需改进",unknown:"无法验证"}};
const outcomeNames={{good_trade_profit:"好交易盈利",good_trade_loss:"好交易亏损",bad_trade_profit:"坏交易盈利",bad_trade_loss:"坏交易亏损",insufficient_evidence:"证据不足",open_trade:"交易进行中"}};
const pnlClass=v=>Number(v)>0?"positive":Number(v)<0?"negative":"";
const netPnl=episode=>Number(episode.realized_pnl||0)-Number(episode.commission||0);
const resultInfo=episode=>episode.status==="open"?{{label:"进行中",cls:"open"}}:netPnl(episode)>=0?{{label:"盈利",cls:"profit"}}:{{label:"亏损",cls:"loss"}};
const processInfo=outcome=>outcome.startsWith("good")?"过程合理":outcome.startsWith("bad")?"过程有问题":outcome==="open_trade"?"尚未完成":"信息不完整";
const dimensionOf=(item,name)=>item.dimensions.find(d=>d.dimension===name);
document.getElementById("subtitle").textContent=`${{data.scope_label}} · ${{new Date(data.created_at).toLocaleString("zh-CN")}} · 所有时间为本地时间`;
const totalNet=Number(data.total_realized_pnl||0)-Number(data.total_commission||0);
document.getElementById("stats").innerHTML=[
  ["交易 Episode",data.episode_count,""],["毛盈亏",money(data.total_realized_pnl),`pnl ${{pnlClass(data.total_realized_pnl)}}`],["手续费",money(data.total_commission),""],["净盈亏（扣费）",money(totalNet),`pnl ${{pnlClass(totalNet)}}`]
].map(x=>`<div class="stat ${{x[2]}}"><small>${{x[0]}}</small><strong>${{x[1]}}</strong></div>`).join("");
document.getElementById("toolbar").innerHTML=layers.map(layer=>`<label class="layer-toggle"><input type="checkbox" checked data-layer="${{layer}}"><span>${{layerNames[layer]}}</span></label>`).join("");
document.getElementById("toolbar").addEventListener("change",e=>{{const layer=e.target.dataset.layer;if(!layer)return;e.target.checked?active.add(layer):active.delete(layer);drawAll();}});
const list=(title,items)=>`<div class="summary"><h2>${{title}}</h2><ul>${{(items.length?items:["暂无足够证据"]).map(x=>`<li>${{escapeHtml(x)}}</li>`).join("")}}</ul></div>`;
document.getElementById("summary").innerHTML=list("做得对",data.top_positives)+list("需要改进",data.top_improvements)+list("重复模式",data.recurring_patterns);
document.getElementById("episode-nav").innerHTML=data.episodes.map((item,index)=>{{const r=resultInfo(item.episode);return `<button data-jump="${{index}}"><b>${{index+1}} · ${{escapeHtml(item.episode.symbol)}} · ${{item.episode.direction==="long"?"多":"空"}}</b><small class="${{r.cls==="profit"?"positive":r.cls==="loss"?"negative":"open"}}">${{r.label}} · 净 ${{money(netPnl(item.episode))}}</small></button>`}}).join("");
document.getElementById("episode-nav").addEventListener("click",e=>{{const button=e.target.closest("[data-jump]");if(button)document.getElementById(`episode-${{button.dataset.jump}}`).scrollIntoView({{behavior:"smooth",block:"start"}});}});
document.getElementById("ledger").innerHTML=`<div class="ledger-head"><h2>逐笔盈亏总表</h2><p>点击任意一行跳到该笔复盘 · 净盈亏 = 已实现盈亏 − 手续费</p></div><div class="trade-table-wrap"><table class="trade-table"><thead><tr><th>#</th><th>合约 / 方向</th><th>开仓 → 平仓</th><th>毛盈亏</th><th>手续费</th><th>净盈亏</th><th>结果</th><th>过程</th><th>最关键的问题 / 优点</th></tr></thead><tbody>${{data.episodes.map((item,index)=>ledgerRow(item,index)).join("")}}</tbody></table></div>`;
document.getElementById("ledger").addEventListener("click",e=>{{const row=e.target.closest("[data-jump]");if(row)document.getElementById(`episode-${{row.dataset.jump}}`).scrollIntoView({{behavior:"smooth",block:"start"}});}});
document.getElementById("episodes").innerHTML=data.episodes.map((item,index)=>episodeHtml(item,index)).join("");
function ledgerRow(item,index){{
  const episode=item.episode,r=resultInfo(episode),key=item.dimensions.find(d=>d.verdict==="improve"&&d.dimension!=="outcome")||item.dimensions.find(d=>d.verdict==="correct")||{{title:"等待交易完成"}};
  return `<tr data-jump="${{index}}"><td>${{index+1}}</td><td><span class="instrument">${{escapeHtml(episode.symbol)}}</span><br>${{episode.direction==="long"?"LONG 做多":"SHORT 做空"}}</td><td class="route">${{episode.entry_price}} → ${{episode.status==="open"?"进行中":episode.exit_price??"—"}}</td><td class="number ${{pnlClass(episode.realized_pnl)}}">${{money(episode.realized_pnl)}}</td><td class="number">${{money(episode.commission)}}</td><td class="number net-value ${{pnlClass(netPnl(episode))}}">${{money(netPnl(episode))}}</td><td><span class="result-badge ${{r.cls}}">${{r.label}}</span></td><td><span class="process-badge">${{processInfo(item.process_outcome)}}</span></td><td class="key-issue">${{escapeHtml(key.title)}}</td></tr>`;
}}
function episodeHtml(item,index){{
  const episode=item.episode, cls=item.process_outcome.startsWith("good")?"good":item.process_outcome.startsWith("bad")?"bad":"unknown";
  const result=resultInfo(episode),brief=decisionBrief(item);
  const chips=item.allocations.map((fill,fillIndex)=>`<button class="trade-chip ${{isEntry(fill)?"open":"close"}}" data-episode="${{index}}" data-fill="${{fillIndex}}"><span class="trade-icon">${{roleCodes[fill.role]||"FILL"}}</span><span><b>${{roleNames[fill.role]||fill.role}} · ${{fill.side}}</b><small>${{fill.price}} × ${{fill.qty}} · ${{formatTime(fill.executed_at)}}</small></span></button>`).join("");
  const panels=["5m","15m","1h","2h","4h"].map(tf=>`<div class="chart-panel ${{tf==="5m"?"active":""}}" data-chart-panel="${{tf}}"><canvas data-episode="${{index}}" data-timeframe="${{tf}}" aria-label="${{episode.symbol}} ${{tf}} K线图"></canvas></div>`).join("");
  const dims=item.dimensions.map(d=>`<div class="dimension ${{d.verdict}}"><header><b>${{escapeHtml(d.title)}}</b><em>${{verdictNames[d.verdict]}}</em></header><p>${{d.evidence.map(escapeHtml).join("<br>")}}</p></div>`).join("");
  const anns=item.annotations.map((a,annIndex)=>`<div class="ann ${{a.verdict}}" data-layer-card="${{a.layer}}" data-episode="${{index}}" data-ann="${{annIndex}}"><div class="ann-meta"><span>${{a.timeframe}} · ${{layerNames[a.layer]}}</span><span>${{a.perspective==="decision_time"?"入场时":"事后"}} · ${{Math.round(a.confidence*100)}}%</span></div><strong>${{escapeHtml(a.label)}}</strong><br>${{escapeHtml(a.evidence)}}</div>`).join("");
  return `<article class="episode" id="episode-${{index}}"><div class="episode-head"><div class="symbol-block"><h2>${{escapeHtml(episode.symbol)}}</h2><p>${{formatDate(episode.opened_at)}} → ${{episode.closed_at?formatDate(episode.closed_at):"进行中"}}</p></div><span class="direction ${{episode.direction}}">${{episode.direction==="long"?"LONG 做多":"SHORT 做空"}}</span><div class="price-route"><b>${{episode.entry_price}}</b><span class="arrow">→</span><b>${{episode.exit_price??"未平仓"}}</b></div><div class="episode-metrics"><div class="metric"><small>成交</small><strong>${{episode.fill_count}} fills</strong></div><span class="outcome ${{cls}}">${{outcomeNames[item.process_outcome]}}</span></div></div><div class="verdict-band"><div class="financial-result ${{result.cls}}"><div><small>这笔交易的财务结果（扣除手续费）</small><strong>${{result.label}} · ${{money(netPnl(episode))}}</strong></div></div><div class="process-result"><div><small>过程评价</small><b>${{processInfo(item.process_outcome)}}</b> <span>毛盈亏 ${{money(episode.realized_pnl)}} · 手续费 ${{money(episode.commission)}}</span></div></div></div><div class="episode-body"><div class="workspace"><div class="decision-brief"><div class="brief-card"><span class="brief-index">01</span><h3>当时背景</h3><p>${{escapeHtml(brief.background)}}</p></div><div class="brief-card ${{brief.openingClass}}"><span class="brief-index">02</span><h3>开仓点位评价</h3><p>${{escapeHtml(brief.opening)}}</p></div><div class="brief-card action"><span class="brief-index">03</span><h3>下次怎么做</h3><p>${{escapeHtml(brief.action)}}</p></div></div><div class="trade-strip" aria-label="成交时间轴">${{chips}}</div><div class="chart-toolbar"><div class="timeframes">${{["5m","15m","1h","2h","4h"].map(tf=>`<button class="tf-button ${{tf==="5m"?"active":""}}" data-episode="${{index}}" data-tf="${{tf}}">${{tf}}</button>`).join("")}}</div><div class="chart-context" id="context-${{index}}"></div><div class="chart-hint">滚轮缩放 · 按住拖拽平移 · 点击成交卡定位</div><div class="chart-tools"><button class="chart-tool" data-chart-zoom="in" data-episode="${{index}}" title="放大K线" aria-label="放大K线">＋</button><button class="chart-tool" data-chart-zoom="out" data-episode="${{index}}" title="缩小K线" aria-label="缩小K线">－</button><button class="chart-tool reset" data-chart-reset data-episode="${{index}}" title="重置图表视窗">复位</button></div></div><div class="chart-stage">${{panels}}<div class="chart-tooltip"></div></div><div class="chart-legend"><span><i></i>EMA20</span><span class="decision"><i></i>入场时证据</span><span class="entry"><i></i>开仓/加仓</span><span class="exit"><i></i>减仓/平仓</span></div></div><aside class="review-side"><div class="side-tabs"><button class="side-tab active" data-side="dimensions">七层审查</button><button class="side-tab" data-side="evidence">图上证据 · ${{item.annotations.length}}</button></div><div class="side-pane active" data-pane="dimensions">${{dims}}</div><div class="side-pane" data-pane="evidence">${{anns}}</div></aside></div></article>`;
}}
function decisionBrief(item){{
  const background=dimensionOf(item,"background"),location=dimensionOf(item,"location"),setup=dimensionOf(item,"setup"),trigger=dimensionOf(item,"trigger"),execution=dimensionOf(item,"execution");
  const high=["4h","2h","1h"].map(tf=>item.charts[tf]?`${{tf}} ${{item.charts[tf].environment}} / AI ${{String(item.charts[tf].always_in).toUpperCase()}}`:"").filter(Boolean).join("；");
  const openingDims=[location,setup,trigger,execution].filter(Boolean),problem=openingDims.find(d=>d.verdict==="improve"),best=openingDims.find(d=>d.verdict==="correct"),opening=problem?`${{problem.title}}。${{problem.evidence[0]||""}}`:best?`${{best.title}}。${{best.evidence[0]||""}}`:"现有成交记录不能完整还原主观计划，只评价可见结构。";
  return {{background:`${{background?.title||"背景待确认"}}。${{high}}`,opening,openingClass:problem?"problem":"",action:nextAction(item)}};
}}
function nextAction(item){{
  const text=item.dimensions.flatMap(d=>[d.title,...d.evidence]).join(" ");
  const actions=[];
  if(/失败的突破|突破失败/.test(text))actions.push("突破失败后停止沿原方向追单，等价格回到区间后出现反向信号，或等待重新突破。");
  if(/追价|突破质量不足|没有同向强突破/.test(text))actions.push("不要追第一下冲出区间；先等 2–3 根同向收盘，或等第一次回调守住突破位。");
  if(/没有可验证 Setup|结构依据偏弱/.test(text))actions.push("下单前写出“背景方向 + 具体 Setup”；写不出 H2/L2、失败突破或突破回调，就不下单。");
  if(/低周期执行缺少同向控制|信号 K 收盘/.test(text))actions.push("5m 等信号 K 收盘并突破极点，再看下一根是否跟随。");
  return (actions.length?actions:["保留当前正确流程：顺高周期、等结构确认、按失效位止损。"]).slice(0,2).join(" ");
}}
function escapeHtml(v){{return String(v).replace(/[&<>"']/g,c=>({{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}}[c]));}}
function formatTime(v){{return new Date(v).toLocaleTimeString("zh-CN",{{hour:"2-digit",minute:"2-digit"}})}}
function formatDate(v){{return new Date(v).toLocaleString("zh-CN",{{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}})}}
function isEntry(fill){{return fill.role==="open"||fill.role==="add"}}
document.getElementById("episodes").addEventListener("click",e=>{{
  const tf=e.target.closest(".tf-button");if(tf){{setTimeframe(Number(tf.dataset.episode),tf.dataset.tf);return;}}
  const chartTool=e.target.closest("[data-chart-zoom],[data-chart-reset]");if(chartTool){{const episode=Number(chartTool.dataset.episode),canvas=document.querySelector(`#episode-${{episode}} .chart-panel.active canvas`);if(!canvas)return;if(chartTool.hasAttribute("data-chart-reset"))resetChart(canvas);else zoomChart(canvas,chartTool.dataset.chartZoom==="in"?-1:1,.5);return;}}
  const tab=e.target.closest(".side-tab");if(tab){{const side=tab.closest(".review-side");side.querySelectorAll(".side-tab").forEach(x=>x.classList.toggle("active",x===tab));side.querySelectorAll(".side-pane").forEach(x=>x.classList.toggle("active",x.dataset.pane===tab.dataset.side));return;}}
  const chip=e.target.closest(".trade-chip");if(chip){{const episode=Number(chip.dataset.episode),fill=Number(chip.dataset.fill);setTimeframe(episode,"5m");document.querySelectorAll(`.trade-chip[data-episode="${{episode}}"]`).forEach(x=>x.classList.toggle("active",x===chip));chartState.set(`focus-${{episode}}`,fill);requestAnimationFrame(()=>focusFill(episode,fill));return;}}
  const ann=e.target.closest(".ann");if(ann){{const episode=Number(ann.dataset.episode),annotation=data.episodes[episode].annotations[Number(ann.dataset.ann)];setTimeframe(episode,annotation.timeframe);return;}}
}});
function setTimeframe(episode,tf){{
  const root=document.getElementById(`episode-${{episode}}`);root.querySelectorAll(".tf-button").forEach(x=>x.classList.toggle("active",x.dataset.tf===tf));root.querySelectorAll(".chart-panel").forEach(x=>x.classList.toggle("active",x.dataset.chartPanel===tf));const chart=data.episodes[episode].charts[tf];document.getElementById(`context-${{episode}}`).innerHTML=`<b>${{escapeHtml(chart.environment)}}</b> · Always-In ${{chart.always_in.toUpperCase()}}`;requestAnimationFrame(()=>drawChart(root.querySelector(`canvas[data-timeframe="${{tf}}"]`),data.episodes[episode],tf));
}}
function drawAll(){{document.querySelectorAll(".chart-panel.active canvas").forEach(canvas=>drawChart(canvas,data.episodes[Number(canvas.dataset.episode)],canvas.dataset.timeframe));document.querySelectorAll("[data-layer-card]").forEach(el=>el.style.display=active.has(el.dataset.layerCard)?"block":"none");}}
function drawEpisode(index){{document.querySelectorAll(`canvas[data-episode="${{index}}"]`).forEach(canvas=>{{if(canvas.closest(".chart-panel").classList.contains("active"))drawChart(canvas,data.episodes[index],canvas.dataset.timeframe)}})}}
function drawChart(canvas,item,tf){{
  const dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;canvas.width=w*dpr;canvas.height=h*dpr;
  const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
  const chart=item.charts[tf],allBars=chart.bars;const episodeIndex=Number(canvas.dataset.episode);document.getElementById(`context-${{episodeIndex}}`).innerHTML=`<b>${{escapeHtml(chart.environment)}}</b> · Always-In ${{chart.always_in.toUpperCase()}}`;
  if(!allBars.length){{ctx.fillStyle="#8896a8";ctx.font="12px sans-serif";ctx.fillText("没有足够行情",20,30);return;}}
  const viewport=normalizeViewport(chartViewport.get(canvas),allBars.length),bars=allBars.slice(viewport.start,viewport.end);chartViewport.set(canvas,viewport);
  canvas.dataset.visibleStart=String(viewport.start);canvas.dataset.visibleEnd=String(viewport.end);canvas.dataset.visibleBars=String(bars.length);
  const pad={{l:18,r:76,t:58,b:28}},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;
  const rangeStart=bars[0].t,rangeEnd=bars.at(-1).t;
  const visibleAnns=item.annotations.filter(a=>a.timeframe===tf&&active.has(a.layer)&&annotationInRange(a,rangeStart,rangeEnd));
  const visibleFills=item.allocations.map((fill,index)=>({{fill,index}})).filter(item=>{{const t=Date.parse(item.fill.executed_at);return t>=rangeStart&&t<=rangeEnd}});
  const prices=bars.flatMap(b=>[b.h,b.l]).concat(visibleAnns.flatMap(a=>a.points.map(p=>Number(p.price)))).concat(visibleFills.map(item=>Number(item.fill.price)));
  let min=Math.min(...prices),max=Math.max(...prices),margin=(max-min||1)*.06;min-=margin;max+=margin;
  const x=i=>pad.l+(i+.5)*pw/bars.length,y=p=>pad.t+(max-p)/(max-min)*ph;
  ctx.strokeStyle="#17212c";ctx.lineWidth=1;for(let i=0;i<=5;i++){{const yy=pad.t+i*ph/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillStyle="#718095";ctx.font="10px "+getComputedStyle(document.documentElement).getPropertyValue("--mono");ctx.fillText((max-i*(max-min)/5).toFixed(priceDigits(max)),w-pad.r+7,yy+3);}}
  for(let i=0;i<=6;i++){{const xx=pad.l+i*pw/6;ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();}}
  visibleAnns.filter(a=>a.shape==="zone"||a.shape==="line").forEach(a=>drawAnnotation(ctx,a,bars,x,y,w,pad));
  const cw=Math.max(1,Math.min(8,pw/bars.length*.68));bars.forEach((b,i)=>{{const up=b.c>=b.o,color=up?"#23c98b":"#f05f70";ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x(i),y(b.h));ctx.lineTo(x(i),y(b.l));ctx.stroke();const top=y(Math.max(b.o,b.c)),bottom=y(Math.min(b.o,b.c));ctx.fillRect(x(i)-cw/2,top,cw,Math.max(1,bottom-top));}});
  ctx.strokeStyle="#f3bd62";ctx.lineWidth=1.3;ctx.beginPath();let moved=false;bars.forEach((b,i)=>{{if(b.ema20==null)return;const yy=y(b.ema20);if(!moved){{ctx.moveTo(x(i),yy);moved=true}}else ctx.lineTo(x(i),yy)}});ctx.stroke();
  drawFills(ctx,visibleFills,bars,x,y,w,h,pad,chartState.get(`focus-${{episodeIndex}}`));
  drawPointAnnotations(ctx,visibleAnns.filter(a=>a.shape!=="zone"&&a.shape!=="line"),bars,x,y,w,h,pad);
  ctx.fillStyle="#718095";ctx.font="10px "+getComputedStyle(document.documentElement).getPropertyValue("--mono");ctx.fillText(formatAxisTime(bars[0].t),pad.l,h-9);ctx.fillText(formatAxisTime(bars.at(-1).t),w-pad.r-84,h-9);
  chartState.set(canvas,{{bars,allBars,x,y,pad,w,h,min,max,start:viewport.start,end:viewport.end}});
}}
function normalizeViewport(viewport,total){{if(!viewport)return {{start:0,end:total}};const count=Math.max(1,Math.min(total,viewport.end-viewport.start)),start=Math.max(0,Math.min(total-count,viewport.start));return {{start,end:start+count}};}}
function redrawCanvas(canvas){{drawChart(canvas,data.episodes[Number(canvas.dataset.episode)],canvas.dataset.timeframe);}}
function zoomChart(canvas,direction,anchorRatio=.5){{const state=chartState.get(canvas);if(!state)return;const total=state.allBars.length,current=state.end-state.start,minBars=Math.min(12,total),next=Math.max(minBars,Math.min(total,Math.round(current*(direction<0?.76:1.3))));if(next===current)return;const anchor=state.start+anchorRatio*current,start=Math.round(anchor-anchorRatio*next);chartViewport.set(canvas,normalizeViewport({{start,end:start+next}},total));redrawCanvas(canvas);}}
function resetChart(canvas){{chartViewport.delete(canvas);redrawCanvas(canvas);}}
function focusFill(episode,fillIndex){{const canvas=document.querySelector(`#episode-${{episode}} .chart-panel.active canvas`),state=chartState.get(canvas),fill=data.episodes[episode].allocations[fillIndex];if(!canvas||!state||!fill)return;const target=nearestIndex(state.allBars,Date.parse(fill.executed_at)),count=Math.min(state.allBars.length,Math.max(24,state.end-state.start)),start=Math.round(target-count/2);chartViewport.set(canvas,normalizeViewport({{start,end:start+count}},state.allBars.length));redrawCanvas(canvas);}}
function annotationInRange(annotation,start,end){{const times=annotation.points.map(p=>Date.parse(p.time)).filter(Number.isFinite);if(!times.length)return false;return Math.min(...times)<=end&&Math.max(...times)>=start;}}
function nearestIndex(bars,time){{let best=0,dist=Infinity;bars.forEach((b,i)=>{{const d=Math.abs(b.t-time);if(d<dist){{dist=d;best=i}}}});return best;}}
function drawFills(ctx,fillItems,bars,x,y,w,h,pad,focused){{
  fillItems.forEach((item,laneIndex)=>{{const fill=item.fill,index=item.index,i=nearestIndex(bars,Date.parse(fill.executed_at)),xx=x(i),yy=y(Number(fill.price)),entry=isEntry(fill),color=entry?"#2d9cff":"#ffb020",soft=entry?"#0e2e4a":"#3c2b15";ctx.save();ctx.strokeStyle=color;ctx.lineWidth=focused===index?2:1;ctx.setLineDash([5,4]);ctx.globalAlpha=(focused===undefined||focused===index) ? 0.9 : 0.42;ctx.beginPath();ctx.moveTo(xx,pad.t-2);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;
    ctx.fillStyle=color;ctx.beginPath();if(entry){{ctx.moveTo(xx,yy-10);ctx.lineTo(xx-8,yy+5);ctx.lineTo(xx+8,yy+5)}}else{{ctx.moveTo(xx,yy+10);ctx.lineTo(xx-8,yy-5);ctx.lineTo(xx+8,yy-5)}}ctx.closePath();ctx.fill();ctx.strokeStyle="#071018";ctx.lineWidth=2;ctx.stroke();
    const label=`${{roleNames[fill.role]||fill.role}}  ${{fill.price}}`,tw=Math.max(88,ctx.measureText(label).width+18),lane=laneIndex%3,ly=8+lane*17,lx=Math.max(pad.l,Math.min(xx-tw/2,w-pad.r-tw));ctx.fillStyle=soft;ctx.strokeStyle=color;ctx.lineWidth=1;ctx.fillRect(lx,ly,tw,15);ctx.strokeRect(lx+.5,ly+.5,tw-1,14);ctx.fillStyle="#f4f8fc";ctx.font="700 9px "+getComputedStyle(document.documentElement).getPropertyValue("--mono");ctx.fillText(label,lx+7,ly+11);ctx.restore();
  }});
}}
function drawAnnotation(ctx,a,bars,x,y,w,pad){{const pts=a.points.map(p=>({{x:x(nearestIndex(bars,Date.parse(p.time))),y:y(Number(p.price))}}));const color=a.verdict==="improve"?"#ff7180":a.verdict==="correct"?"#4dd69d":"#7f8da0";ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1;ctx.setLineDash(a.perspective==="decision_time"?[4,3]:[]);
  if(a.shape==="zone"&&pts.length>1){{const top=Math.min(pts[0].y,pts[1].y),bottom=Math.max(pts[0].y,pts[1].y);ctx.globalAlpha=.06;ctx.fillRect(pad.l,top,w-pad.l-pad.r,bottom-top);ctx.globalAlpha=.7;ctx.strokeRect(pad.l,top,w-pad.l-pad.r,bottom-top);}}
  else if(a.shape==="line"&&pts.length>1){{ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(pad.l,pts[0].y);ctx.lineTo(w-pad.r,pts.at(-1).y);ctx.stroke();}}
  else if(pts.length){{ctx.globalAlpha=.78;ctx.beginPath();ctx.arc(pts[0].x,pts[0].y,3,0,Math.PI*2);ctx.fill();}}ctx.globalAlpha=1;ctx.setLineDash([]);
}}
function drawPointAnnotations(ctx,annotations,bars,x,y,w,h,pad){{
  const occupied=[],bottom=h-pad.b-3;
  annotations.map(a=>{{const point=a.points[0],anchor={{x:x(nearestIndex(bars,Date.parse(point.time))),y:y(Number(point.price))}};return {{a,anchor}}}}).sort((left,right)=>left.anchor.x-right.anchor.x||left.anchor.y-right.anchor.y).forEach(item=>{{
    const {{a,anchor}}=item,color=a.verdict==="improve"?"#ff7180":a.verdict==="correct"?"#4dd69d":"#7f8da0",lines=wrapLabel(a.label),font="600 9px "+getComputedStyle(document.documentElement).getPropertyValue("--sans");ctx.font=font;
    const boxW=Math.min(176,Math.max(72,...lines.map(line=>ctx.measureText(line).width+14))),boxH=lines.length*12+8,baseX=Math.max(pad.l+3,Math.min(anchor.x+7,w-pad.r-boxW-3));let box=null;
    const offsets=[-boxH-7,8,-boxH-41,42,-boxH-75,76,-boxH-109,110];
    for(const offset of offsets){{const candidate={{x:baseX,y:Math.max(pad.t+3,Math.min(bottom-boxH,anchor.y+offset)),w:boxW,h:boxH}};if(!occupied.some(other=>boxesOverlap(candidate,other))){{box=candidate;break}}}}
    if(!box){{for(let lane=0;lane<10;lane++){{const candidate={{x:Math.max(pad.l+3,Math.min(w-pad.r-boxW-3,baseX+(lane%2?-(lane+1)*18:(lane+1)*18))),y:pad.t+4+(lane%5)*(boxH+4),w:boxW,h:boxH}};if(candidate.y+boxH<=bottom&&!occupied.some(other=>boxesOverlap(candidate,other))){{box=candidate;break}}}}}}
    if(!box)return;occupied.push(box);ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=.68;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(anchor.x,anchor.y);ctx.lineTo(Math.max(box.x,Math.min(anchor.x,box.x+box.w)),Math.max(box.y,Math.min(anchor.y,box.y+box.h)));ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle="rgba(9,14,20,.94)";ctx.fillRect(box.x,box.y,box.w,box.h);ctx.strokeStyle=color;ctx.strokeRect(box.x+.5,box.y+.5,box.w-1,box.h-1);ctx.fillStyle="#eef4fa";ctx.font=font;lines.forEach((line,index)=>ctx.fillText(line,box.x+7,box.y+12+index*12));ctx.restore();
  }});
}}
function wrapLabel(value){{const text=String(value),limit=16;if(text.length<=limit)return [text];const first=text.slice(0,limit),rest=text.slice(limit);return [first,rest.length>limit?rest.slice(0,limit-1)+"…":rest];}}
function boxesOverlap(a,b){{const gap=4;return !(a.x+a.w+gap<b.x||b.x+b.w+gap<a.x||a.y+a.h+gap<b.y||b.y+b.h+gap<a.y);}}
function formatAxisTime(v){{return new Date(v).toLocaleString("zh-CN",{{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}})}}
function priceDigits(value){{return value>=1000?1:value>=10?3:5}}
function bindPointer(canvas){{
  const stage=canvas.closest(".chart-stage"),tip=stage.querySelector(".chart-tooltip");
  let drag=null;
  canvas.addEventListener("wheel",e=>{{e.preventDefault();const state=chartState.get(canvas);if(!state)return;const rect=canvas.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-rect.left-state.pad.l)/(state.w-state.pad.l-state.pad.r)));zoomChart(canvas,e.deltaY<0?-1:1,ratio);}},{{passive:false}});
  canvas.addEventListener("pointerdown",e=>{{if(e.button!==0)return;const state=chartState.get(canvas);if(!state)return;drag={{x:e.clientX,start:state.start,end:state.end}};canvas.classList.add("dragging");canvas.setPointerCapture?.(e.pointerId);tip.style.display="none";}});
  canvas.addEventListener("pointermove",e=>{{const state=chartState.get(canvas);if(!state)return;if(drag){{const count=drag.end-drag.start,plotWidth=state.w-state.pad.l-state.pad.r,shift=Math.round((drag.x-e.clientX)/Math.max(1,plotWidth)*count);chartViewport.set(canvas,normalizeViewport({{start:drag.start+shift,end:drag.end+shift}},state.allBars.length));redrawCanvas(canvas);return;}}const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,index=Math.max(0,Math.min(state.bars.length-1,Math.floor((mx-state.pad.l)/(state.w-state.pad.l-state.pad.r)*state.bars.length))),b=state.bars[index];tip.innerHTML=`<b>${{formatAxisTime(b.t)}}</b><br>O ${{b.o}}　H ${{b.h}}<br>L ${{b.l}}　C ${{b.c}}<br>EMA20 ${{b.ema20==null?"—":Number(b.ema20).toFixed(priceDigits(b.c))}}`;tip.style.display="block";tip.style.left=Math.min(mx+14,state.w-190)+"px";tip.style.top=Math.max(8,Math.min(my+14,state.h-92))+"px";}});
  const stopDrag=e=>{{if(!drag)return;drag=null;canvas.classList.remove("dragging");canvas.releasePointerCapture?.(e.pointerId);}};canvas.addEventListener("pointerup",stopDrag);canvas.addEventListener("pointercancel",stopDrag);
  canvas.addEventListener("mouseleave",()=>{{if(!drag)tip.style.display="none"}});
}}
document.querySelectorAll("canvas").forEach(bindPointer);
let resizeTimer;window.addEventListener("resize",()=>{{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawAll,100)}});
data.episodes.forEach((_,index)=>setTimeframe(index,"5m"));drawAll();
</script></body></html>"""
